### ISSUE TITLE
Insiders and WSL2

### ISSUE THREAD

**Issue by jongio** [VarthanV/pypi-tracker#1]
Doesn't seem to work with Code Insiders latest and WSL2.

Can you see if it works for you?

Nothing gets printed to the PyPI Watcher log.

**Comment by VarthanV** [comment]
Yeah i will look into it ,Thanks

**Comment by VarthanV** [comment]
Can you pls show me the Screenshots of the issue ?

**Comment by jongio** [comment]
Just nothing happens.  Not much to screenshot.

**Comment by VarthanV** [comment]
Ok ill see to it

**Comment by jongio** [comment]
Let me know if you want to setup a call so you can see it not working and try to debug with me.

**Comment by VarthanV** [comment]
Yeah im interested figuring out the issue , wish to set up a call with you

**Comment by jongio** [comment]
Okay, please DM me on Twitter or contact me here: https://jong.io/contact

**Comment by VarthanV** [comment]
I submitted sir.
